### ISSUE TITLE
ARM Template UI's 

### ISSUE THREAD

**Issue by baltic-dev** [balticapprenticeships/Azure-Templates#10]
We need additional functionality to enable the validation of passwords when creating virtual machines for all deployment templates. 
This will require the following to be completed:

- [x] Design a new UI
- [x] Add a password confirmation field for the admin and standard user accounts with regex validation.
- [x] Test the UI to deploy multiple VMs
 Similar to #9

**Comment by cnomadl** [comment]
All items completed and tested.
