### ISSUE TITLE
ARM Template UI

### ISSUE THREAD

**Issue by baltic-dev** [balticapprenticeships/Azure-Templates#9]
We need additional functionality to enable the validation of passwords when creating virtual machines, also the ability to select either a Windows or Linux OS

**Comment by cnomadl** [comment]
A new full UI will be required to enable the password validation and OS selection.

- [ ] Design a new UI.
- [ ] Add password confirmation field for the admin and standard user accounts with regex validation.
- [ ] Allow the selection of Windows or Linux and hide fields such as SSH when Windows is selected.
- [ ] Test UI to deploy 1 and multiple Windows VMs.
- [ ] Test UI to deploy 1 or more Linux VMs.

**Comment by cnomadl** [comment]
Review completed and the code accepted for production.
